spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.5.200:3306/WMS
    username: root
    password: 123456
  data:
    redis:
      host: 192.168.5.200
      port: 6379
mybatis:
  configuration:

    map-underscore-to-camel-case: true
